version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
    network_mode: "host"